# .github/workflows/ci-release.yml
name: CI & Release

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 4️⃣ TypeScript type check
      - name: Type check
        run: pnpm run typecheck
        continue-on-error: false

      # 5️⃣ Lint
      - name: Lint-Scripts
        run: pnpm run lint
        continue-on-error: false

      # 7️⃣ Build
      - name: Build
        run: pnpm run build

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish to npm & GitHub

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js with npm registry
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
