# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ TypeScript type check
      - name: Type check
        run: npm run typecheck
        continue-on-error: false

      # 5️⃣ Lint scrips
      - name: Lint
        run: npm run lint
        continue-on-error: false

      # 6️⃣ Run tests
      - name: Run tests
        run: npm test -- --passWithNoTests
        continue-on-error: false

      # 7️⃣ Build library
      - name: Build
        run: npm run build
        continue-on-error: false
